export const scoreCard = {
  frames: [
    {
      frameNumber: 1,
      first: '1',
      second: '3',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 4,
      nextTwoBowls: [],
    },
    {
      frameNumber: 2,
      first: '3',
      second: '3',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 10,
      nextTwoBowls: [],
    },
    {
      frameNumber: 3,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 4,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 5,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 6,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 7,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 8,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 9,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 10,
      first: '',
      second: '',
      third: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
  ],
}

const updatedScoreCardWithNextTwoBowls = {
  frames: [
    {
      frameNumber: 1,
      first: '1',
      second: '3',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 4,
      nextTwoBowls: [3, 3],
    },
    {
      frameNumber: 2,
      first: '3',
      second: '3',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 10,
      nextTwoBowls: [],
    },
    {
      frameNumber: 3,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 4,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 5,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 6,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 7,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 8,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 9,
      first: '',
      second: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
    {
      frameNumber: 10,
      first: '',
      second: '',
      third: '',
      didPrevFrameStrike: false,
      didPrevFrameSpare: false,
      totalScore: 0,
      nextTwoBowls: [],
    },
  ],
}
